import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

type Props = {
  title: "string";
};

export default function Home({ title }: Props) {
  return (
    <>
      <Head>
        <title>Event App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img src="" alt="" />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About us</a>
        </nav>
      </header>

      <h1>{title}</h1>

      <main className={styles.main}>
        <a href="">
          <img />
          <h2>Events in London</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic cum ea
            provident maxime autem. Id deleniti sapiente tempore voluptatem
            necessitatibus molestiae sequi earum, ea rem dolor iure temporibus
            est aperiam vel asperiores cumque. Recusandae neque nihil sint
            minima enim. Delectus earum quo voluptate tempora enim quod
            aspernatur corrupti maiores vero!
          </p>
        </a>

        <a href="">
          <img />
          <h2>Events in San Francisco</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic cum ea
            provident maxime autem. Id deleniti sapiente tempore voluptatem
            necessitatibus molestiae sequi earum, ea rem dolor iure temporibus
            est aperiam vel asperiores cumque. Recusandae neque nihil sint
            minima enim. Delectus earum quo voluptate tempora enim quod
            aspernatur corrupti maiores vero!
          </p>
        </a>

        <a href="">
          <img />
          <h2>Events in Bacelona</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic cum ea
            provident maxime autem. Id deleniti sapiente tempore voluptatem
            necessitatibus molestiae sequi earum, ea rem dolor iure temporibus
            est aperiam vel asperiores cumque. Recusandae neque nihil sint
            minima enim. Delectus earum quo voluptate tempora enim quod
            aspernatur corrupti maiores vero!
          </p>
        </a>
      </main>

      <footer className={styles.footer}>
        <p> © 2023 Coding time - A Project Built with Next.js </p>
      </footer>
    </>
  );
}

export function getServerSideProps() {
  return {
    props: {
      title: "Hello everyone",
    },
  };
}
